--   ======================================================================================
--    AUTOGENERATED!!!! DO NOT EDIT!!!!
--   ======================================================================================

{% set union_all = joiner("UNION ALL") %}
CREATE OR REPLACE VIEW {{ target_table.full_name }}
AS
SELECT
  {{ target_table.root_key.name }}
  {% for key in target_table.keys %}
  ,{{ key.name }}
  {% endfor %}
  ,{{ target_table.load_dts.name }}
  ,{{ target_table.rec_src.name }}
FROM (
  SELECT
    {{ target_table.root_key.name }}
    {% for key in target_table.keys %}
    ,{{ key.name }}
    {% endfor %}
    ,{{ target_table.load_dts.name }}
    ,{{ target_table.rec_src.name }}
    ,row_number() over(PARTITION BY {{ target_table.root_key.name }} ORDER BY {{ target_table.load_dts.name }} asc) rn
  FROM (
    {% for source_table in mappings.source_tables(target_table) %}
    {% set source_filter = mappings.filter(source_table, target_table) %}
    {% set concat = joiner(" || '|' || ") %}
    {{ union_all() }}
    SELECT
      {%+ for key in target_table.keys %}{{ concat() }}{{ mappings.source_column(source_table, key) }}{% endfor %} AS {{ target_table.root_key.name }}
      {% for key in target_table.keys %}
      ,{{ mappings.source_column(source_table, key) }} AS {{ key.name }}
      {% endfor %}
      ,{{ mappings.source_column(source_table, target_table.load_dts) }} AS {{ target_table.load_dts.name }}
      ,{{ mappings.source_column(source_table, target_table.rec_src) }} AS {{ target_table.rec_src.name }}
    FROM {{ source_table.full_name }}
    {% if source_filter %}
    WHERE {{ source_filter }}
    {% endif %}
    {% endfor %}
  ) res1
) res2
WHERE rn = 1
;
