--   ======================================================================================
--    AUTOGENERATED!!!! DO NOT EDIT!!!!
--   ======================================================================================

{% set union_all = joiner("UNION ALL") %}
{% set insert_ = target_table.properties.generate_type == 'table' %}
{% if target_table.properties.generate_type == 'view' %}
DROP VIEW IF EXISTS {{ target_table.full_name }};

CREATE VIEW {{ target_table.full_name }}
AS
{% endif %}
{% if insert_ %}
INSERT INTO {{ target_table.full_name }}
{% endif %}
SELECT
  {{ target_table.root_key.name }}
  {% for key in target_table.keys %}
  ,{{ key.name }}
  {% endfor %}
  ,{{ target_table.load_dts.name }}
  ,{{ target_table.rec_src.name }}
FROM (
  SELECT
    {{ target_table.root_key.name }}
    {% for key in target_table.keys %}
    ,{{ key.name }}
    {% endfor %}
    ,{{ target_table.load_dts.name }}
    ,{{ target_table.rec_src.name }}
    ,row_number() over(PARTITION BY {{ target_table.root_key.name }} ORDER BY {{ target_table.load_dts.name }} asc) rn
  FROM (
    {% for source_table in mappings.source_tables(target_table) %}
    {% set source_filter = mappings.filter(source_table, target_table) %}
    {% set concat = joiner(" || '|' || ") %}
    {{ union_all() }}
    SELECT
      {%+ for key in target_table.keys %}{{ concat() }}{{ mappings.source_column(source_table, key) }}{% endfor %} AS {{ target_table.root_key.name }}
      {% for key in target_table.keys %}
      ,{{ mappings.source_column(source_table, key) }} AS {{ key.name }}
      {% endfor %}
      ,{{ mappings.source_column(source_table, target_table.load_dts) }} AS {{ target_table.load_dts.name }}
      ,{{ mappings.source_column(source_table, target_table.rec_src) }} AS {{ target_table.rec_src.name }}
    FROM {{ source_table.full_name }}
    {% if source_filter or insert_ %}
    WHERE
      {% set and_ = joiner("AND ") %}
      {% if source_filter %}{{ and_() }}{{ source_filter }}{% endif %}
      {% if insert_ %}
      {{ and_() }}:start_ts <= {{ mappings.source_column(source_table, target_table.load_dts) }}
      AND {{ mappings.source_column(source_table, target_table.load_dts) }} < :end_ts
      {% endif %}
    {% endif %}
    {% endfor %}
  )
  {% if insert_ %}
  AS q
  WHERE
    NOT EXISTS (
      SELECT 1
      FROM {{ target_table.full_name }} t
      WHERE t.{{ target_table.root_key.name }} = q.{{ target_table.root_key.name }}
    )
  {% endif %}
)
WHERE rn = 1
;
