--   ======================================================================================
--    AUTOGENERATED!!!! DO NOT EDIT!!!!
--   ======================================================================================

{% set source_table = mappings.source_tables(target_table)[0] %}
{% set source_filter = mappings.filter(source_table, target_table) %}
CREATE OR REPLACE VIEW {{ target_table.full_name }}
AS
SELECT
  {{ target_table.key.name }}
  ,max({{ target_table.load_dts.name }}) AS {{ target_table.load_dts.name }}
  {% for attribute in target_table.attributes %}
  ,{{ attribute.name }}
  {% endfor %}
  ,{{ mappings.source_column(source_table, target_table.rec_src) }} AS {{ target_table.rec_src.name }}
FROM (
  SELECT
    {{ mappings.source_column(source_table, target_table.key) }} AS {{ target_table.key.name }}
    ,{{ mappings.source_column(source_table, target_table.load_dts) }} AS {{ target_table.load_dts.name }}
    {% for attribute in target_table.attributes %}
    ,{{ mappings.source_column(source_table, attribute) }} AS {{ attribute.name }}
    {% endfor %}
  FROM
    {{ source_table.full_name }}
  {% if source_filter %}
  WHERE
    {{ source_filter }}
  {% endif %}
)
GROUP BY
  {{ target_table.key.name }}
  {% for attribute in target_table.attributes %}
  ,{{ attribute.name }}
  {% endfor %}
;
