--Hub that uses GROUP BY ON bk
CREATE OR REPLACE VIEW DV.customer_h AS
SELECT SOCIAL_SECURITY_NUMBER AS customer_key ,
       SOCIAL_SECURITY_NUMBER ,
       'edge' AS REC_SRC ,
       min(_SDC_RECEIVED_AT) AS LOAD_DTS
FROM SRC_EDGE.customer
GROUP BY SOCIAL_SECURITY_NUMBER;
