#Hub that uses GROUP BY ON bk
CREATE OR REPLACE VIEW groupby_h AS
SELECT SOCIAL_SECURITY_NUMBER AS customer_key ,
       SOCIAL_SECURITY_NUMBER ,
       'edge' AS REC_SRC ,
       max(_SDC_RECEIVED_AT) AS LOAD_DTS
FROM customer
GROUP BY SOCIAL_SECURITY_NUMBER;
